Repository SamSam-kakotechboot/travel_FE, pull requests merged in 2024-07, with the labels that each got.

#2 docs: pr 템플릿 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📝 문서화

#3 feat: 티켓 상세조회 페이지 목업
  node_modules/.vite/deps/@reduxjs_toolkit.js
  node_modules/.vite/deps/@reduxjs_toolkit.js.map
  node_modules/.vite/deps/_metadata.json
  node_modules/.vite/deps/chunk-4HAMFFQC.js
  node_modules/.vite/deps/chunk-4HAMFFQC.js.map
  node_modules/.vite/deps/chunk-EQCVQC35.js
  node_modules/.vite/deps/chunk-EQCVQC35.js.map
  node_modules/.vite/deps/chunk-PBXWVHXV.js
  node_modules/.vite/deps/chunk-PBXWVHXV.js.map
  node_modules/.vite/deps/package.json
  node_modules/.vite/deps/react-dom_client.js
  node_modules/.vite/deps/react-dom_client.js.map
  node_modules/.vite/deps/react-redux.js
  node_modules/.vite/deps/react-redux.js.map
  node_modules/.vite/deps/react-router-dom.js
  node_modules/.vite/deps/react-router-dom.js.map
  node_modules/.vite/deps/react.js
  node_modules/.vite/deps/react.js.map
  node_modules/.vite/deps/react_jsx-dev-runtime.js
  node_modules/.vite/deps/react_jsx-dev-runtime.js.map
  node_modules/.vite/deps/react_jsx-runtime.js
  node_modules/.vite/deps/react_jsx-runtime.js.map
  src/App.jsx
  src/assets/half_star.svg
  src/assets/info.svg
  src/assets/star.svg
  src/components/HomeProduct.jsx
  src/components/KeywordRectangle.jsx
  src/components/TicketDetail.jsx
  src/components/TicketInfo.jsx
  src/components/Tickets.jsx
  src/components/icons/HalfStarIcon.jsx
  src/components/icons/InfoIcon.jsx
  src/components/icons/StarIcon.jsx
Labels: 💡 기능 개발, 🎨 디자인

#5 feat: 리뷰 조회 페이지 목업
  src/components/BlackButton.jsx
  src/components/Review.jsx
  src/components/Reviews.jsx
  src/components/TicketDetail.jsx
  src/components/TicketInfo.jsx
Labels: ⚙️ 리팩토링, 🎨 디자인

#7 feat: 리뷰 작성 폼 페이지 목업
  src/App.jsx
  src/components/ReviewForm.jsx
  src/components/Reviews.jsx
  src/components/TicketInfo.jsx
  src/components/Tooltip.jsx
  src/components/UploadButton.jsx
  src/components/icons/GrayStarIcon.jsx
  src/components/icons/UploadIcon.jsx
Labels: ⚙️ 리팩토링, 🎨 디자인

#8 feat: route 방식 수정
  src/App.jsx
  src/components/Cart.jsx
  src/components/Home.jsx
  src/components/Login.jsx
  src/components/LoginButton.jsx
  src/components/LoginId.jsx
  src/components/LoginModal.jsx
  src/components/LoginName.jsx
  src/components/LoginPassword.jsx
  src/components/LoginPhone.jsx
  src/components/LoginRemember.jsx
  src/components/MyOrder.jsx
  src/components/ReviewForm.jsx
  src/components/TicketDetail.jsx
  src/components/Tickets.jsx
  src/main.jsx
  src/router.jsx
Labels: ⚙️ 리팩토링, 💡 기능 개발, 🎨 디자인

#9 feat: 상품 상태 관리 추가 및 리팩토링
  src/assets/disneyland.png
  src/components/Home.jsx
  src/components/HomeProduct.jsx
  src/components/PageButtons.jsx
  src/components/ReviewForm.jsx
  src/components/Reviews.jsx
  src/components/TicketDetail.jsx
  src/components/TicketInfo.jsx
  src/components/Tickets.jsx
  src/router.jsx
  src/testdata/ticket.json
Labels: ⚙️ 리팩토링, 💡 기능 개발
