Repository SamSam-kakotechboot/travel_FE, pull requests merged in 2024-08, with the labels that each got.

#10 feat: 리뷰 조회 상태 관리 코드 추가 및 리팩토링
  src/assets/disneyland_review.png
  src/components/Review.jsx
  src/components/Reviews.jsx
  src/components/Tickets.jsx
  src/testdata/review.json
  src/testdata/ticket.json
  src/utils/pagination.js
Labels: ⚙️ 리팩토링, 💡 기능 개발

#11 fix: 디렉토리 구조 리팩토링 및 티켓 데이터 조회 로직 수정
  src/pages/Cart.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/MyOrder.jsx
  src/pages/TicketDetail.jsx
  src/pages/Tickets.jsx
  src/router.jsx
Labels: 🚨 버그 해결, ⚙️ 리팩토링

#12 feat: 로그인/로그아웃 기능 구현 및 리팩토링
  src/components/KeywordRectangle.jsx
  src/components/LoginId.jsx
  src/components/LoginInput.jsx
  src/components/LoginModal.jsx
  src/components/LoginName.jsx
  src/components/LoginPassword.jsx
  src/components/MyOrderList.jsx
  src/hooks/loginApi.js
  src/hooks/loginApireal.js
  src/hooks/loginHook.js
  src/main.jsx
  src/pages/Cart.jsx
  src/pages/MyOrder.jsx
  src/router.jsx
  src/store/authSlice.js
  src/store/store.js
  src/testdata/login.json
  src/utils/authAction.js
  src/utils/cookie.js
Labels: ⚙️ 리팩토링, 💡 기능 개발, 🎨 디자인

#14 refact: Auth 로직 리팩토링
  src/components/CartDetail.jsx
  src/components/HomeProduct.jsx
  src/components/Star.jsx
  src/components/TicketInfo.jsx
  src/pages/Home.jsx
  src/pages/TicketDetail.jsx
  src/pages/Tickets.jsx
  src/router.jsx
  src/store/cartSlice.js
  src/store/store.js
  src/testdata/ticket.json
  src/testdata/ticketall.json
  src/utils/loader.js
Labels: 🚨 버그 해결, ⚙️ 리팩토링

#15 feat: 나의 리뷰 조회 컴포넌트 추가
  src/assets/writing.svg
  src/components/MyOrderList.jsx
  src/components/MyReviewList.jsx
  src/pages/MyPage.jsx
  src/router.jsx
  src/utils/authAction.js
Labels: 💡 기능 개발, 🎨 디자인
